apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444
    - name: node
      protocol: TCP
      port: 5555
      targetPort: 5555

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub-deployment
  labels:
    app: selenium-hub
    name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/standalone-chrome:latest
          env:
            - name: JAVA_OPTS
              value: "-Xmx1024m"
            - name: POOL_MAX
              value: "500"
            - name: GRID_NEW_SESSION_WAIT_TIMEOUT
              value: "-1"
            - name: GRID_JETTY_MAX_THREADS
              value: "-1"
            - name: GRID_NODE_POLLING
              value: "5000"
            - name: GRID_CLEAN_UP_CYCLE
              value: "5000"
            - name: GRID_TIMEOUT
              value: "600"
            - name: GRID_BROWSER_TIMEOUT
              value: "600"
            - name: GRID_MAX_SESSION
              value: "5"
            - name: GRID_UNREGISTER_IF_STILL_DOWN_AFTER
              value: "30000"
          ports:
            - containerPort: 4444
              protocol: TCP